language: php

php: 5.6

services:
  - docker

jobs:
  include:
    - stage: test
      name: Run test in PHP 5.6
      script: ./phpunit.sh 5.6
    - name: Run test in PHP 7.0
      script: ./phpunit.sh 7.0
    - name: Run test in PHP 7.1
        script: ./phpunit.sh 7.1
    - name: Run test in PHP 7.2
        script: ./phpunit.sh 7.2
    - name: Run test in PHP 7.3
        script: ./phpunit.sh 7.3
