language: php

php: 5.6

services:
  - docker

before_install:
  - docker pull php:5.6
  - docker pull php:7.0
  - docker pull php:7.1
  - docker pull php:7.2
  - docker pull php:7.3

script:
  - composer install
  - ./phpunit.sh 5.6
  - ./phpunit.sh 7.0
  - ./phpunit.sh 7.1
  - ./phpunit.sh 7.2
  - ./phpunit.sh 7.3
