<?php

namespace HTMLDomParserTests;

use PHPUnit\Framework\TestCase;

/**
 * Class DomTest
 * @package HTMLDomParserTests
 */
class DomTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
